### PR TITLE
added processData.R

### PR DESCRIPTION
**Pull request by mansarin**
which is an R script that can download tar files, untar them, and run logtools on them. still working on a few things, but functions work.

### CODE REVIEW

**Comment by jecollins** [comment]
Ideally this code would be platform-neutral, but perhaps we can leave that for another update, perhaps when someone else wants to use it on Linux or Mac. Generally I like to put platform-specific stuff into command-line args or environment variables.

**Comment by mansarin** [comment]
That's my intent too. I think the only Windows-dependent code in there is the shell() command. The folders need to be adjusted per use case, I imagine.

**Comment by mansarin** [comment]
Regarding the shell() call, it's easy to solve: system() is a more generic call, but I haven't yet figured out how to make that work in Windows. If I can't, I'll set up an if-else for the OS.

**Comment by mansarin** [comment]
I noticed I had not committed the new R file before submitting a pull request. I just did that and hopefully it should be there now. It's call processData.R

**Comment by jecollins** [comment]
If MainWindows.py is part of this PR, then why does it appear (twice) in .gitignore?

**Comment by mansarin** [comment]
I intended to add it once. I updated MainWindows.py to match some changes in the other functions so that it still works. But then I added it to gitignore to avoid committing changes when I only change a folder location or logtool name. Does this make sense?

**Comment by jecollins** [comment]
This is really not an appropriate use of .gitignore. The result of this change is that future changes to MainWindows.py will not be committed unless the user understands that they have to manually add it to the commit. Better to just do manual adds of other changes when some module in the repo is not ready to be committed.

**Comment by mansarin** [comment]
I have removed .gitignore's two instances of MainWindows.py and also updated processData.R (more functions).

**Comment by erikkemperman** [comment]
@mansarin I wondered about how to ignore tracked files once as well, I find this a useful trick:
https://stackoverflow.com/questions/17195861/undo-git-update-index-assume-unchanged-file

**Comment by mansarin** [comment]
ok, gitignore and processData.R should look as I expect now. ProcessData.R should also now work on a UNIX-based system (can anybody verify this?)

@erikkemperman thanks.

**Pull request merged**
